apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: lxkyed90h-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-fd5d8c0f65.ot65.p3.openshiftapps.com/rhtap/rhtap-qe:1b92dee7c9dda147cbb157ea6a796292c6763832@sha256:fb2f1d154239cff694f100f708d4dfa9b4e26356ccf5ebf8bad976b5e9312ff0
          name: container-image
